# Generated by Django 5.0.6 on 2024-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
    ]
