# Generated by Django 5.0.6 on 2024-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_auto_20240624_1130'),
    ]

    operations = [
    ]
