# Generated by Django 5.0.6 on 2024-06-26 08:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_author_rubrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programming.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 26, 8, 32, 8, 900025, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Biographie à compléter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrique',
            name='description',
            field=models.TextField(default='Description à compléter'),
            preserve_default=False,
        ),
     migrations.AlterField(
    model_name='article',
    name='rubrique',
    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programming.rubrique'),
    preserve_default=False,
),

        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
