# Generated by Django 5.0.6 on 2024-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240624_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_pub',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rubrique',
        ),
        migrations.RemoveField(
            model_name='article',
            name='titre',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Titre par défaut', max_length=200),
            preserve_default=False,
        ),
    ]
