# Generated by Django 5.0.6 on 2024-06-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecurite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
