# Generated by Django 5.0.6 on 2024-06-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecurite', '0004_rename_title_rubrique_name_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersecurite.author'),
        ),
    ]
